<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="com.oracle.sim.testcases.SupplierLookup.SupplierLookupAddressExpansion" tests="2" time="0.003" ignored="0" failures="1" timestamp="28 Jul 2020 10:18:24 GMT" skipped="1" hostname="LAPAI-IN" errors="0">
  <testcase name="setup" time="0.000" classname="com.oracle.sim.testcases.SupplierLookup.SupplierLookupAddressExpansion">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [Store Inventory Operations Cloud Service] but found []">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [Store Inventory Operations Cloud Service] but found []
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at com.oracle.core.base.CoreBasePage.verifyTextValue(CoreBasePage.java:78)
	at com.oracle.sim.testcases.SupplierLookup.SupplierLookupAddressExpansion.setup(SupplierLookupAddressExpansion.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:217)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:144)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:169)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
    </failure>
  </testcase> <!-- setup -->
  <testcase name="supplierAddressFieldsVerify" time="0.003" classname="com.oracle.sim.testcases.SupplierLookup.SupplierLookupAddressExpansion">
    <skipped/>
  </testcase> <!-- supplierAddressFieldsVerify -->
</testsuite> <!-- com.oracle.sim.testcases.SupplierLookup.SupplierLookupAddressExpansion -->
